spring:
  datasource:
    url: jdbc:mysql://localhost:3306/find_my_match
    username: root
    password: Mydb@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true